import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'sonner'
import { Poppins } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({ weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Social Clout | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Toaster richColors position="top-center" />
        {children}
        <NextTopLoader showSpinner={false} color="red" height={4} />
      </body>
    </html>
  );
}
